Update Dockerfile
When running docker-compose build for the first time on a new build the build errors out with:


Installing mini_portile2 2.3.0
Fetching nokogiri 1.8.5
Installing nokogiri 1.8.5 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/ext/nokogiri
/usr/local/bin/ruby -I /usr/local/lib/ruby/site_ruby/2.4.0 -r
./siteconf20181229-10-ikjtmk.rb extconf.rb --with-iconv-lib\=/usr/local/lib\
--with-iconv-include\=/usr/local/include
checking if the C compiler accepts ... yes
Building nokogiri using packaged libraries.
Using mini_portile version 2.3.0
checking for gzdopen() in -lz... yes
checking for iconv using --with-iconv-* flags... yes
************************************************************************
IMPORTANT NOTICE:

Building Nokogiri with a packaged version of libxml2-2.9.8
with the following patches applied:
        - 0001-Revert-Do-not-URI-escape-in-server-side-includes.patch
        - 0002-Fix-nullptr-deref-with-XPath-logic-ops.patch
        - 0003-Fix-infinite-loop-in-LZMA-decompression.patch

Team Nokogiri will keep on doing their best to provide security
updates in a timely manner, but if this is a concern for you and want
to use the system library instead; abort this installation process and
reinstall nokogiri as follows:

    gem install nokogiri -- --use-system-libraries
        [--with-xml2-config=/path/to/xml2-config]
        [--with-xslt-config=/path/to/xslt-config]

If you are using Bundler, tell it to use the option:

    bundle config build.nokogiri --use-system-libraries
    bundle install

Note, however, that nokogiri is not fully compatible with arbitrary
versions of libxml2 provided by OS/package vendors.
************************************************************************
Extracting libxml2-2.9.8.tar.gz into
tmp/x86_64-pc-linux-musl/ports/libxml2/2.9.8... OK
Running git apply with
/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/patches/libxml2/0001-Revert-Do-not-URI-escape-in-server-side-includes.patch...
OK
Running git apply with
/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/patches/libxml2/0002-Fix-nullptr-deref-with-XPath-logic-ops.patch...
OK
Running git apply with
/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/patches/libxml2/0003-Fix-infinite-loop-in-LZMA-decompression.patch...
OK
Running 'configure' for libxml2 2.9.8... ERROR, review
'/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/ext/nokogiri/tmp/x86_64-pc-linux-musl/ports/libxml2/2.9.8/configure.log'
to see what happened. Last lines are:
========================================================================
checking whether to enable maintainer-specific portions of Makefiles... yes
checking build system type... x86_64-pc-linux-gnu
checking host system type... x86_64-pc-linux-musl
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for x86_64-pc-linux-musl-strip... no
checking for strip... strip
checking for a thread-safe mkdir -p... ./install-sh -c -d
checking for gawk... no
checking for mawk... no
checking for nawk... no
checking for awk... awk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for x86_64-pc-linux-musl-gcc... gcc
checking whether the C compiler works... no
configure: error: in
`/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5/ext/nokogiri/tmp/x86_64-pc-linux-musl/ports/libxml2/2.9.8/libxml2-2.9.8':
configure: error: C compiler cannot create executables
See `config.log' for more details
========================================================================
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/$(RUBY_BASE_NAME)
        --help
        --clean
        --use-system-libraries
        --enable-static
        --disable-static
        --with-zlib-dir
        --without-zlib-dir
        --with-zlib-include
        --without-zlib-include=${zlib-dir}/include
        --with-zlib-lib
        --without-zlib-lib=${zlib-dir}/lib
        --enable-cross-build
        --disable-cross-build
/mastodon/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:402:in
`block in execute': Failed to complete configure task (RuntimeError)
from
/mastodon/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:373:in
`chdir'
from
/mastodon/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:373:in
`execute'
from
/mastodon/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:110:in
`configure'
from
/mastodon/vendor/bundle/ruby/2.4.0/gems/mini_portile2-2.3.0/lib/mini_portile2/mini_portile.rb:153:in
`cook'
        from extconf.rb:365:in `block (2 levels) in process_recipe'
        from extconf.rb:257:in `block in chdir_for_build'
        from extconf.rb:256:in `chdir'
        from extconf.rb:256:in `chdir_for_build'
        from extconf.rb:364:in `block in process_recipe'
        from extconf.rb:262:in `tap'
        from extconf.rb:262:in `process_recipe'
        from extconf.rb:551:in `<main>'

To see why this extension failed to compile, please check the mkmf.log which can
be found here:

/mastodon/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/nokogiri-1.8.5/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/mastodon/vendor/bundle/ruby/2.4.0/gems/nokogiri-1.8.5 for inspection.
Results logged to
/mastodon/vendor/bundle/ruby/2.4.0/extensions/x86_64-linux/2.4.0/nokogiri-1.8.5/gem_make.out

An error occurred while installing nokogiri (1.8.5), and Bundler cannot
continue.
Make sure that `gem install nokogiri -v '1.8.5' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rails-settings-cached was resolved to 0.6.6, which depends on
    rails was resolved to 5.2.1, which depends on
      actioncable was resolved to 5.2.1, which depends on
        actionpack was resolved to 5.2.1, which depends on
          actionview was resolved to 5.2.1, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri
ERROR: Service 'streaming' failed to build: The command '/bin/sh -c bundle config build.nokogiri --with-iconv-lib=/usr/local/lib --with-iconv-include=/usr/local/include  && bundle install -j$(getconf _NPROCESSORS_ONLN) --deployment --without test development  && yarn install --pure-lockfile --ignore-engines  && yarn cache clean' returned a non-zero code: 5